// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xpath.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Xpath module
	public static java.util.List<xpath.proxies.Example> dS_ExampleReport(IContext context, xpath.proxies.ExampleReport_DataGrid _paging)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Paging", _paging == null ? null : _paging.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Xpath.DS_ExampleReport").withParams(params).execute(context);
		java.util.List<xpath.proxies.Example> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(xpath.proxies.Example.initialize(context, obj));
		}
		return result;
	}
	public static void example1(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Xpath.example1").withParams(params).execute(context);
	}
}