// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xpath.proxies;

public class ExampleReport_DataGrid extends system.proxies.Paging
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Xpath.ExampleReport_DataGrid";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Count("Count"),
		TotalPages("TotalPages"),
		PageSize("PageSize"),
		Filter_Value("Filter_Value"),
		Filter_Date_lower("Filter_Date_lower"),
		Filter_Date_Upper("Filter_Date_Upper"),
		PageNumber("PageNumber"),
		IsSortable("IsSortable"),
		SortAttribute("SortAttribute"),
		SortAscending("SortAscending"),
		HasMoreData("HasMoreData");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ExampleReport_DataGrid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Xpath.ExampleReport_DataGrid"));
	}

	protected ExampleReport_DataGrid(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject exampleReport_DataGridMendixObject)
	{
		super(context, exampleReport_DataGridMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Xpath.ExampleReport_DataGrid", exampleReport_DataGridMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Xpath.ExampleReport_DataGrid");
	}

	/**
	 * @deprecated Use 'ExampleReport_DataGrid.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static xpath.proxies.ExampleReport_DataGrid initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return xpath.proxies.ExampleReport_DataGrid.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static xpath.proxies.ExampleReport_DataGrid initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new xpath.proxies.ExampleReport_DataGrid(context, mendixObject);
	}

	public static xpath.proxies.ExampleReport_DataGrid load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return xpath.proxies.ExampleReport_DataGrid.initialize(context, mendixObject);
	}

	/**
	 * @return value of Count
	 */
	public final java.lang.Integer getCount()
	{
		return getCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Count
	 */
	public final java.lang.Integer getCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Count.toString());
	}

	/**
	 * Set value of Count
	 * @param count
	 */
	public final void setCount(java.lang.Integer count)
	{
		setCount(getContext(), count);
	}

	/**
	 * Set value of Count
	 * @param context
	 * @param count
	 */
	public final void setCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer count)
	{
		getMendixObject().setValue(context, MemberNames.Count.toString(), count);
	}

	/**
	 * @return value of TotalPages
	 */
	public final java.lang.Integer getTotalPages()
	{
		return getTotalPages(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalPages
	 */
	public final java.lang.Integer getTotalPages(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalPages.toString());
	}

	/**
	 * Set value of TotalPages
	 * @param totalpages
	 */
	public final void setTotalPages(java.lang.Integer totalpages)
	{
		setTotalPages(getContext(), totalpages);
	}

	/**
	 * Set value of TotalPages
	 * @param context
	 * @param totalpages
	 */
	public final void setTotalPages(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalpages)
	{
		getMendixObject().setValue(context, MemberNames.TotalPages.toString(), totalpages);
	}

	/**
	 * Set value of PageSize
	 * @param pagesize
	 */
	public final xpath.proxies.PageSize getPageSize()
	{
		return getPageSize(getContext());
	}

	/**
	 * @param context
	 * @return value of PageSize
	 */
	public final xpath.proxies.PageSize getPageSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PageSize.toString());
		if (obj == null)
			return null;

		return xpath.proxies.PageSize.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of PageSize
	 * @param pagesize
	 */
	public final void setPageSize(xpath.proxies.PageSize pagesize)
	{
		setPageSize(getContext(), pagesize);
	}

	/**
	 * Set value of PageSize
	 * @param context
	 * @param pagesize
	 */
	public final void setPageSize(com.mendix.systemwideinterfaces.core.IContext context, xpath.proxies.PageSize pagesize)
	{
		if (pagesize != null)
			getMendixObject().setValue(context, MemberNames.PageSize.toString(), pagesize.toString());
		else
			getMendixObject().setValue(context, MemberNames.PageSize.toString(), null);
	}

	/**
	 * @return value of Filter_Value
	 */
	public final java.lang.String getFilter_Value()
	{
		return getFilter_Value(getContext());
	}

	/**
	 * @param context
	 * @return value of Filter_Value
	 */
	public final java.lang.String getFilter_Value(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Filter_Value.toString());
	}

	/**
	 * Set value of Filter_Value
	 * @param filter_value
	 */
	public final void setFilter_Value(java.lang.String filter_value)
	{
		setFilter_Value(getContext(), filter_value);
	}

	/**
	 * Set value of Filter_Value
	 * @param context
	 * @param filter_value
	 */
	public final void setFilter_Value(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String filter_value)
	{
		getMendixObject().setValue(context, MemberNames.Filter_Value.toString(), filter_value);
	}

	/**
	 * @return value of Filter_Date_lower
	 */
	public final java.util.Date getFilter_Date_lower()
	{
		return getFilter_Date_lower(getContext());
	}

	/**
	 * @param context
	 * @return value of Filter_Date_lower
	 */
	public final java.util.Date getFilter_Date_lower(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Filter_Date_lower.toString());
	}

	/**
	 * Set value of Filter_Date_lower
	 * @param filter_date_lower
	 */
	public final void setFilter_Date_lower(java.util.Date filter_date_lower)
	{
		setFilter_Date_lower(getContext(), filter_date_lower);
	}

	/**
	 * Set value of Filter_Date_lower
	 * @param context
	 * @param filter_date_lower
	 */
	public final void setFilter_Date_lower(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date filter_date_lower)
	{
		getMendixObject().setValue(context, MemberNames.Filter_Date_lower.toString(), filter_date_lower);
	}

	/**
	 * @return value of Filter_Date_Upper
	 */
	public final java.util.Date getFilter_Date_Upper()
	{
		return getFilter_Date_Upper(getContext());
	}

	/**
	 * @param context
	 * @return value of Filter_Date_Upper
	 */
	public final java.util.Date getFilter_Date_Upper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Filter_Date_Upper.toString());
	}

	/**
	 * Set value of Filter_Date_Upper
	 * @param filter_date_upper
	 */
	public final void setFilter_Date_Upper(java.util.Date filter_date_upper)
	{
		setFilter_Date_Upper(getContext(), filter_date_upper);
	}

	/**
	 * Set value of Filter_Date_Upper
	 * @param context
	 * @param filter_date_upper
	 */
	public final void setFilter_Date_Upper(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date filter_date_upper)
	{
		getMendixObject().setValue(context, MemberNames.Filter_Date_Upper.toString(), filter_date_upper);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final xpath.proxies.ExampleReport_DataGrid that = (xpath.proxies.ExampleReport_DataGrid) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Xpath.ExampleReport_DataGrid";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
